# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2af3231951fdd71893f97f37c2a924e7a035dadec22a01096e5a544d04af7bf70e89cfcbbbbe236eba772638c46927956eff56cbcc7bfc062e7eb2a0db1e58f
  twitter_consumer_key: 8x5KPWjDOGYWI90b6AtP7dtYb
  twitter_consumer_secret: KTmEWCxXfuKW4F8nsWHWuq0zKTzgjez5CpOlpQHUqCFJ2WTxEO
  twitter_access_token: 3366435496-oVWg5rx8R8bynUDeg3YofuCyDOSp3AyRs8mQISS
  twitter_access_token_secret: bQCAbAhPrIL7qEWLeM15A6P9TAzsYLrRZoJJ6d52aKMrm
  
test:
  secret_key_base: 394131cfb9b6247e412ee5d2ef93ef493c3deed40dc38f5b4f2ff6ef119237be75103a08a1af584241ea8ff40cc0bdbf309c9b00fbb5b06049977f7e8e66f8ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
